env:
 global:
   - CC_TEST_REPORTER_ID=89f368f110c6d2f0ed7cba650ff40888b2b28333f7cc3b425c450dbf7f536d36

language: node_js

node_js:
 - lts/*

cache:
  directories:
    - "node_modules"

install: npm install

before_script:
 - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
 - chmod +x ./cc-test-reporter
 - ./cc-test-reporter before-build

script:
 - make lint
 - npm test

after_script:
 - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

notifications:
 email: false
